title: SOTEREL
description: "Collectif de citoyens développant des outils pour la soutenabilité territoriale et la résilience locale en se basant sur la permaculture."
lang: fr_FR
logo: ""
image: ""
twitter:
  card: summary_large_image

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: "assets/img"
    values:
      image: true
